### ISSUE TITLE
# compile and install volepsi

### ISSUE THREAD

**Issue by fffmath** [lx-1234/MPSU#3]
When I run the following code "cp volepsi/out/build/linux/volePSI/config.h ../libvolepsi/include/volePSI/", it tell me there is no volepsi/out/build/linux. I don't know where the problem is.

By the way, I think there exisits a typo that "python3 python3 build.py --install=../libvolepsi". It should be "python3 build.py --install=../libvolepsi"?

**Comment by fffmath** [comment]
I think maybe "cp out/build/linux/volePSI/config.h ../libvolepsi/include/volePSI/" is right :)

**Comment by fffmath** [comment]
Update: I successfully reproduced the code, and those above are minor issues. Thanks for the author's good work!

**Comment by lx-1234** [comment]
thx for your correction. I have fixed the typos ;)
